version: 2

sources:
  - name: interview_source
    schema: 'interview_source'
    tables:
      - name: raw_sync_events
        description: "These events are produced by this twilio webhook: https://www.twilio.com/docs/sync/webhooks#map-event-request-parameters"
        columns:
          - name: "MapSid"
            description: "Uid created by twilio corresponding to the sync map which generated this event"
          - name: "EventType"
            description: "The type of event. The vast majority of the records will be map_item_updated, but map_created, map_item_added are also valid values"
          - name: "DateCreated"
            description: "This is the DateCreated for the event, can be thought of as EventTimestamp"
          - name: "MapRevision"
            description: "This is an monotonically increasing integer, incremented for each change made to the Map (stored as a HEX string)."
          - name: "ProtocolVersion"
            description: "This is an monotonically increasing integer, incremented for each change made to the Map (stored as a HEX string)."
          - name: "AccountSid"
            description: "Dwelo's Twilio account id. It is 34 characters long, and always starts with the letters AC."
          - name: "ItemKey"
            description: "The key of the item in the map that was added, updated, or removed."
          - name: "EndpointId"
            description: "The server-assigned EndpointId for the Sync client (Hub, cloudapi, etc) that generated the event. EndpointId is generated by Twilio gateways."
          - name: "EventId"
            description: "A sequence number representing the order of occurrence for the map item event."
          - name: "ServiceSid"
            description: "The unique id for the service instance."
          - name: "ItemRevision"
            description: "This is an monotonically increasing integer, incremented for each change made to the Item (stored as a HEX string)."
          - name: "Identity"
            description: "The username/identity of the user that generated the event. Identity is originally supplied in the client authentication token."
          - name: "IsIdentityOnline"
            description: "A boolean that shows if the identity is online or offline when a reachability event is emitted. If set to true, the supplied identity has one or more active connections. Note: the identity could have multiple endpoints connected, represented by different EndpointId's on various transports (i.e. websocket and MQTT)."
          - name: "ListSid"
            description: "The list id. It is 34 characters long, and always starts with the letters ES."
          - name: "ListUniqueName"
            description: "The unique name of the list."
          - name: "MapUniqueName"
            description: "The unique name of the Map. In Dwelo's case for map_item_udpated events this maps to the device_id associated with this map."
          - name: "_source_file"
            description: "The path to the raw s3 object in which this event was stored on it's through the data pipeline."
          - name: "_scheduled_timestamp"
            description: "Timestamp recording the time at which the batch containing this event was loaded to BigQuery"
          - name: "ItemData"
            description: "The data for the MapItem as JSON. Structure varies by ItemKey *** This is where a lot of the useful info is stored for parsing events ***
            *** Part One ***
              -- ItemKey = Command
                uuid: A uuid corresponding to a single command
                timestamp: A timestamp generated by the cloudapi when this command was issued.
                client: The type of client that issued the command. ios/android/googlehome
                user: The user_id of the user that issued the command
                desired_state[]: This is an array for which the first index indicates the command, subsequent indexes depend on that context
                -- First the simple ones:
                  0: One of LockedState/ThermostatMode/ThermostatHeatSetPoint/SwitchState/LockedState/ThermostatCoolSetPoint
                  1: The value to which the 0th index should be set. For example [\"SwitchState\",\"off\"]
                -- PinAssignment has a different pattern
                  0: PinAssignment
                  1: The memory slot on the lock to set the pin on
                  2: The pin to set
                -- As does DimmerState
                  0: DimmerState
                  1: Multilevel On/Multilevel Off
                  2: The level to set the dimmer to if any
              -- ItemKey = CommandActive
                uuid: The uuid to which this CommandActive update corresponds.
                timestamp: A timestamp generated by the hub when it picked this command off the MQTT stream
                node_id: The node id of the device to which dispatch was planned on the hub
              -- ItemKey = CommandResult
                uuid: The uuid to which this CommandResult update corresponds.
                timestamp: A timestamp generated by the hub when it dispatched this command over zwave
                node_id: The node id on the hub of the device to which this command was dispatched
                result: A boolean true/false indicating whether the hub successfully dispatched this command to the device
                failure_string: An optional string providing additional troubleshooting information in the case of the result = false

            *** Part Three ***
              -- ItemKey = ThermostatOperatingState
                state: The state of the thermostat Heat/Heat2/Idle
                timestamp: A timestamp generated by the hub when it received this reading over zwave
              -- ItemKey = ThermostatCoolSetpoint
                state.value: Integer or float representing the cool setpoint of the thermostat
                state.unit: F or C indicating whehter the units are being reported in Fahrenheit or Celsius
                timestamp: A timestamp generated by the hub when it received this reading over zwave
              -- ItemKey = ThermostatHeatSetpoint
                state.value: Integer or float representing the heat setpoint of the thermostat
                state.unit: F or C indicating whehter the units are being reported in Fahrenheit or Celsius
                timestamp: A timestamp generated by the hub when it received this reading over zwave
              -- ItemKey = ThermostatMode
                state: The mode of the thermostat Off/Cool/Heat/Auto
                timestamp: A timestamp generated by the hub when it received this reading over zwave
              -- ItemKey = Switch
                state.value: The state of the switch; On or Off
                timestamp: A timestamp generated by the hub when it received this reading over zwave
              -- ItemKey = DoorLocked
                state: A boolean string where true indicates locked
                timestamp: A timestamp generated by the hub when it received this reading over zwave
              -- ItemKey = Dimmer
                state.value: The state of the switch; On or Off
                state.percent: An integer value provided when switch is On indicating the percentage of the dimmer level
                timestamp: A timestamp generated by the hub when it received this reading over zwave
              "

      - name: raw_users
        columns:
          - name: "uid"
          - name: "username"
          - name: "dateRegistered"
          - name: "last_modified"
models:
  - name: stg_commands
    description: "Commands"
    columns:
      - name: command_uuid
        description: "A unique identifier of a command. The primary key for this table"
        tests:
          - not_null
          - unique
      - name: command_client
        description: "The type of client that issued this command"
      - name: thermostat_set_point
        description: "Thermostat set point"
      - name: thermostat_mode
        description: "Thermostat Mode"
      - name: slot
        description: "Slot"
      - name: pin
        description: "Pin"
      - name: switch_state
        description: "state of the switch"
      - name: dimmer_state
        description: "state of the dimmer"
      - name: dimmer_level
        description: "dimmer level"
      - name: lock_state
        description: "lock state"
      - name: _raw_desired_state
        description: "The guts of the command, the target state for the device"
        tests:
          - not_null
      - name: user_id
        description: "The user that issued this command"
        tests:
          - not_null
      - name: update_timestamp
        description: "Timestamp from Twilio for when the device map was updated by the hub"
        tests:
          - not_null
      - name: event_timestamp
        description: "Timestamp generated at the client for this event"
      - name: device_id
        description: "The device_id of the targeted device"
        tests:
          - not_null
      - name: _uid
        description: "global uid for sync map updates"
      - name: _source_file
        description: "The source file that this update was in on it's way to our data warehouse"
  - name: stg_command_actives
    description: "CommandActive responses from hubs"
    columns:
      - name: command_uuid
        description: "A unique identifier of a command. The primary key for this table"
        tests:
          - not_null
          - unique
      - name: command_node_id
        description: "The node id the command was dispatched to on the hub"
      - name: update_timestamp
        description: "Timestamp from Twilio for when the device map was updated by the hub"
        tests:
          - not_null
      - name: event_timestamp
        description: "Timestamp generated at the client for this event"
      - name: device_id
        description: "The device_id of the targeted device"
      - name: _source_file
        description: "The source file that this update was in on it's way to our data warehouse"
  - name: stg_command_results
    description: "CommandResult responses from hubs"
    columns:
      - name: command_uuid
        description: "A unique identifier of a command. The primary key for this table"
        tests:
          - not_null
          - unique
      - name: is_hub_success
        description: "A boolean value with is True when the $.result field from a CommandResult contains 'success' or 'true'"
        tests:
          - not_null
      - name: command_failure_string
        description: "A on optional string provided by the hub when is_hub_success is false describing additional info about the failure"
      - name: command_node_id
        description: "The node id the command was dispatched to on the hub"
      - name: update_timestamp
        description: "Timestamp from Twilio for when the device map was updated by the hub"
        tests:
          - not_null
      - name: event_timestamp
        description: "Timestamp generated at the client for this event"
      - name: device_id
        description: "The device_id of the targeted device"
      - name: _source_file
        description: "The source file that this update was in on it's way to our data warehouse"
  - name: stg_users
    description: "Users"
    columns:
      - name: user_id
        description: "The user id"
        tests:
          - not_null
          - unique
      - name: username
        description: "The user's username"
        tests:
          - not_null
          - unique
      - name: date_registered
        description: "A timestamp when a user first registered an account"
        tests:
          - not_null
      - name: last_modified
        description: "A timestamp when the user record was last modified"
        tests:
          - not_null
